#!/bin/bash

without_port() {
  scp -P $PORT -r [!.]* $USER_NAME@$IP_ADDR:~/ostack
}

with_port() {
  read -p "Enter port number:" PORT
  scp -P $PORT -r [!.]* $USER_NAME@$IP_ADDR:~/ostack
}

read -p "Enter Username: " USER_NAME
read -p "Enter IP Address: " IP_ADDR
read -p "Use Specific Port [Y/N]: " USE_PORT

case "${USE_PORT}" in
  Y) with_port
      ;;
  y) with_port
      ;;
  N) without_port
      ;;
  n) without_port
      ;;
  *) echo "Input invalid. Please choose between [Y/N]."
     echo "Operation aborted."
     exit
esac
