#!/bin/bash

source server

without_port() {
  scp -r [!.]* $ALL_USERNAME@$IP_ADDR:~/ostack
}

with_port() {
  read -p "Enter port number:" PORT
  scp -P $PORT -r [!.]* $ALL_USERNAME@$IP_ADDR:~/ostack
}

read -p "Enter IP Address: " IP_ADDR
read -p "Use Specific Port [Y/N]: " USE_PORT

case "${USE_PORT}" in
  Y) with_port
      ;;
  y) with_port
      ;;
  N) without_port
      ;;
  n) without_port
      ;;
  *) echo "Input invalid. Please choose between [Y/N]."
     echo "Operation aborted."
     exit
esac
