#!/bin/bash

source ../services

echo " "
echo "==================================================================================="
echo "Add compute node to NOVA cell database on '$(hostname)'"
echo "==================================================================================="
echo " "
echo "WARNING! Make sure you have configure NOVA on COMPUTE node and "
echo "execute it with the user which load '~/ostack-openrc/admin-openrc' "
echo "to his enviroment variable"
echo " "
echo " $ . ~/ostack-openrc/admin-openrc"
echo " "
echo " OR"
echo " "
echo " $ source ~/ostack-openrc/admin-openrc"
echo " "
echo "==================================================================================="
echo " "

read -n1 -r -p "Discover compute host. press ENTER to continue!" ENTER
sudo su -s /bin/sh -c "nova-manage cell_v2 discover_hosts --verbose" nova

echo "[OSTACK] Nova on '$(hostname)' done."

echo " "
echo "==================================================================================="
echo "POST INSTALLATION NOTE"
echo "==================================================================================="
echo "Load the 'admin-openrc' file to populate environment variables."
echo "It will also load the location of keystone and admin project and user credentials:"
echo " "
echo " $ . ~/ostack-openrc/admin-openrc"
echo " "
echo " OR"
echo " "
echo " $ source ~/ostack-openrc/admin-openrc"
echo " "
echo "Execute 'controller/nova/7_conf_nova.sh' after successfully configure new compute."
echo "Then execute it to list service components to verify the compute successfully"
echo "configured and every process was registered:"
echo " "
echo " $ openstack compute service list"
echo " "
echo "List API endpoints in keystone to verify connection with keystone:"
echo " "
echo " $ openstack catalog list"
echo " "
echo "List images in keystone to verify connectivity with glance:"
echo " "
echo " $ openstack image list"
echo " "
echo "Login as root and Check the cells and placement API are working successfully:"
echo " "
echo " # nova-status upgrade check"
echo " "
echo "==================================================================================="
echo " "
