#!/bin/bash

source ../../services
source ../../servers

conf_keystone() {
  echo "======================================================="
  echo "[OSTACK] Configure ${SERVICE_NAME1}"
  echo "======================================================="

  if [[ -d /etc/${SERVICE_NAME1} ]]; then
    echo "[OSTACK] Configuring ${SERVICE_NAME1} database.."
    if [[ -f /etc/${SERVICE_NAME1}/${SERVICE_NAME1}.conf.ori ]]; then
      echo "[OSTACK] Orginal config found, create temporary config backup.."
      sed -i.bak -e "605d" /etc/${SERVICE_NAME1}/${SERVICE_NAME1}.conf
      echo "[OSTACK] Setting connection.."
      sed -i "605i -l connection = mysql+pymysql://${SERVICE_NAME1}:${KEYSTONE_DBPASS}@controller/${SERVICE_NAME1}" /etc/${SERVICE_NAME1}/${SERVICE_NAME1}.conf
      echo "[OSTACK] Done."
    else
      echo "[OSTACK] Original config not found, create original config backup.."
      sed -i.ori -e "605d" /etc/${SERVICE_NAME1}/${SERVICE_NAME1}.conf
      echo "[OSTACK] Setting connection.."
      sed -i "605i -l connection = mysql+pymysql://${SERVICE_NAME1}:${KEYSTONE_DBPASS}@controller/${SERVICE_NAME1}" /etc/${SERVICE_NAME1}/${SERVICE_NAME1}.conf
      echo "[OSTACK] Done."
    fi

    echo "[OSTACK] Configuring ${SERVICE_NAME1} token.."
    if [[ -f /etc/${SERVICE_NAME1}/${SERVICE_NAME1}.conf.ori ]]; then
      echo "[OSTACK] Orginal config found, create temporary config backup.."
      sed -i.bak -e "1271d" /etc/${SERVICE_NAME1}/${SERVICE_NAME1}.conf
      echo "[OSTACK] Setting provider.."
      sed -i "1271i -l provider = fernet" /etc/${SERVICE_NAME1}/${SERVICE_NAME1}.conf
      echo "[OSTACK] Done."
    else
      echo "[OSTACK] Orginal config not found, create original config backup.."
      sed -i.ori -e "1271d" /etc/${SERVICE_NAME1}/${SERVICE_NAME1}.conf
      echo "[OSTACK] Setting provider.."
      sed -i "1271i -l provider = fernet" /etc/${SERVICE_NAME1}/${SERVICE_NAME1}.conf
      echo "[OSTACK] Done."
    fi

    echo "[OSTACK] Populate ${SERVICE_NAME1} database.."
    su -s /bin/sh -c "keystone-manage db_sync" ${SERVICE_NAME1}

    echo "[OSTACK] Initialize Fernet key repositories.."
    keystone-manage fernet_setup --keystone-user ${SERVICE_NAME1} --keystone-group ${SERVICE_NAME1}
    keystone-manage credential_setup --keystone-user ${SERVICE_NAME1} --keystone-group ${SERVICE_NAME1}

    echo "[OSTACK] Bootstraping ${SERVICE_NAME1}.."
    keystone-manage bootstrap --bootstrap-password ${KEYSTONE_ADMINPASS} --bootstrap-admin-url http://controller:35357/v3/ --bootstrap-internal-url http://controller:35357/v3/ --bootstrap-public-url http://controller:5000/v3/ --bootstrap-region-id RegionOne

    echo "[OSTACK] Done."
    conf_apache2
  else
    echo "[OSTACK] Chrony is not installed. Execute 'dep_conf_env_controller' first!"
    echo "[OSTACK] Abort."
    exit
  fi
}

conf_apache2() {
  echo "======================================================="
  echo "[OSTACK] Configure HTTP server"
  echo "======================================================="

  if [[ -d /etc/apache2 ]]; then
    echo "[OSTACK] Configuring the Apache HTTP server.."
    if [[ -f /etc/apache2/apache2.conf.ori ]]; then
      echo "[OSTACK] Orginal config found, create temporary config backup.."
      cp /etc/apache2/apache2.conf /etc/apache2/apache2.conf.bak

      echo "[OSTACK] Setting ServerName.."
      cat >> /etc/apache2/apache2.conf <<EOF

# Openstack ServerName
ServerName ${IP_ADDR0_ETH1}
EOF
    else
      echo "[OSTACK] Orginal config not found, creating backup.."
      cp /etc/apache2/apache2.conf /etc/apache2/apache2.conf.ori

      echo "[OSTACK] Setting ServerName.."
      cat >> /etc/apache2/apache2.conf <<EOF

# Openstack ServerName
ServerName ${IP_ADDR0_ETH1}
EOF
    fi

    echo "[OSTACK] Restarting apache2.."
    service apache2 restart

    echo "[OSTACK] Removing default SQlite database"
    rm -f /var/lib/keystone/keystone.db

    echo "[OSTACK] Done."
    set_enviroment
  else
    echo "[OSTACK] Chrony is not installed. Execute 'dep_conf_env_controller' first!"
    echo "[OSTACK] Abort."
    exit
  fi
}

set_enviroment() {
  echo "======================================================="
  echo "[OSTACK] Set enviroment variable"
  echo "======================================================="

  echo "[OSTACK] Setting enviroment.."
  . admin-openrc

  echo "[OSTACK] Done."
  service_project
}

service_project() {
  echo "======================================================="
  echo "[OSTACK] Create project"
  echo "======================================================="

  echo "[OSTACK] Creating service project.."
  openstack project create --domain default --description "Service Project" service

  echo "[OSTACK] Creating demo project.."
  openstack project create --domain default --description "Demo Project" demo

  echo "[OSTACK] Creating demo user.."
  openstack user create --domain default --password-prompt demo

  echo "[OSTACK] Creatingrole.."
  openstack role create user

  echo "[OSTACK] Add the user role to the demo project and use"
  openstack role add --project demo --user demo user

  echo "[OSTACK] Done."
  verify_keystone
}

verify_keystone() {
  echo "======================================================="
  echo "[OSTACK] Verify keystone"
  echo "======================================================="

  echo "[OSTACK] Unset the temporary OS_AUTH_URL and OS_PASSWORD environment variable.."
  unset OS_AUTH_URL OS_PASSWORD

  echo "[OSTACK] As the admin user, request an authentication token.."
  openstack --os-auth-url http://controller:35357/v3 --os-project-domain-name Default --os-user-domain-name Default --os-project-name admin --os-username admin token issue

  echo "[OSTACK] As the demo user, request an authentication token.."
  openstack --os-auth-url http://controller:5000/v3 --os-project-domain-name Default --os-user-domain-name Default --os-project-name demo --os-username demo token issue

  echo "[OSTACK] Done."
  env_var
}

env_var() {
  echo "[OSTACK] Copying admin-openrc to /home/${USERNAME0}.."
  cp admin-openrc /home/${USERNAME0}/

  echo "[OSTACK] Copying demo-openrc to /home/${USERNAME0}.."
  cp demo-openrc /home/${USERNAME0}/

  echo "[OSTACK] Done."
  export_admin
}

export_admin() {
  echo "[OSTACK] Exporting admin-openrc.."
  . /home/${USERNAME0}/admin-openrc

  echo "[OSTACK] Done."
  token_issue
}

token_issue() {
  echo "[OSTACK] Requesting an authentication token.."
  openstack token issue

  echo "[OSTACK] Finish."
}

echo "[OSTACK] CONFIGURING '${SERVICE_NAME1}' ON '$(hostname)'.."
conf_keystone
