#!/bin/bash

echo "======================================================="
echo "[OSTACK] Install NTP chrony.."
echo "======================================================="
apt install -y chrony

echo "======================================================="
echo "[OSTACK] Update and upgrade server.."
echo "======================================================="
apt update && apt dist-upgrade -y

echo "======================================================="
echo "[OSTACK] Enable openstack repositories.."
echo "======================================================="
apt install -y software-properties-common
add-apt-repository cloud-archive:ocata

echo "======================================================="
echo "[OSTACK] Install python-openstackclient.."
echo "======================================================="
apt install -y python-openstackclient

echo "======================================================="
echo "[OSTACK] Install mariadb-server and python-pymysql.."
echo "======================================================="
apt install -y mariadb-server python-pymysql

echo "======================================================="
echo "[OSTACK] Install rabbitmq-server.."
echo "======================================================="
apt install -y rabbitmq-server

echo "======================================================="
echo "[OSTACK] Install memcached and python-memcache.."
echo "======================================================="
apt install -y memcached python-memcache
